name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and upload with Gradle
      env:
        TGBOT_TOKEN: ${{ secrets.TGBOTTOKEN }}
        TGBOT_CHATID: ${{ secrets.TGBOTCHATID }}
        SERVER_TOKEN: ${{ secrets.SERVERTOKEN }}
      run: ./gradlew :app:uploadDebugArtifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
